dist: xenial

language: c
os:
  - linux

git:
  depth: 3

env:
  matrix:
    - BUILD=Debug    BUILD_CC=gcc
    - BUILD=Release  BUILD_CC=gcc
    - BUILD=Debug    BUILD_CC=clang
    - BUILD=Release  BUILD_CC=clang

script:
  - |
    cd $TRAVIS_BUILD_DIR
    rm -rf build
    mkdir build
    cd build
    cmake -DCMAKE_C_COMPILER=$BUILD_CC -DCMAKE_BUILD_TYPE=$BUILD ..
    make
